logout:
    path:   /admin/logout

login:
    path:     /login
    defaults: { _controller: UnetworkAdminBundle:Security:login }
    
login_check:
    path: /admin/login_check

unetwork_app:
    resource: "@UnetworkAppBundle/Controller/"

    type:     annotation
    prefix:   /

unetwork_admin:
    resource: "@UnetworkAdminBundle/Controller/"

    type:     annotation
    prefix:   /

unetwork_public:
    resource: "@UnetworkPublicBundle/Controller/"
    type:     annotation
    prefix:   /

