
unetwork_app:
    resource: "@UnetworkAppBundle/Controller/"

    type:     annotation
    prefix:   /

unetwork_admin:
    resource: "@UnetworkAdminBundle/Controller/"

    type:     annotation
    prefix:   /

unetwork_public:
    resource: "@UnetworkPublicBundle/Controller/"
    type:     annotation
    prefix:   /

