# app/config/security.yml
security:
    encoders:
        Unetwork\AdminBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        administrators:
            entity: { class: UnetworkAdminBundle:User, property: email }

    firewalls:
        admin_area:
            pattern:    ^/
            anonymous: ~
            logout:
                path:   /logout
                target: /
            form_login:
                login_path: /login
                check_path: /login_check

    access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/app, roles: ROLE_USER }